DELETE http://localhost:8080/events/1
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBvZ2xvZ0Bwb2cuY29tIiwiZXhwIjoxNzI3ODk4MDkyLCJ1c2VySWQiOjF9.NifyhOHaVCz1wBU00mc1B0Wuy-1JG98vfQXSYRVxeTE